import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import os
import requests
import io
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configure the Streamlit page
st.set_page_config(
    page_title="Rhocash AP Hiring Intelligence",
    page_icon="💼",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for modern premium styling
st.markdown("""
<style>
    /* Dark Premium Theme */
    .stApp {
        background-color: #0E1117;
        color: #FAFAFA;
    }
    .main .block-container {
        padding-top: 2rem;
    }
    
    /* Sleek Metric Cards */
    .metric-card {
        background: linear-gradient(145deg, #1A1C23, #15171C);
        padding: 24px;
        border-radius: 12px;
        border: 1px solid #2D3139;
        box-shadow: 0 4px 20px rgba(0,0,0,0.4);
        text-align: center;
        transition: transform 0.2s ease, box-shadow 0.2s ease;
    }
    .metric-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 8px 30px rgba(0,0,0,0.6);
        border-color: #3B82F6;
    }
    .metric-value {
        font-size: 2.8rem;
        font-weight: 800;
        background: -webkit-linear-gradient(#60A5FA, #3B82F6);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 5px;
    }
    .metric-label {
        font-size: 0.95rem;
        color: #9CA3AF;
        text-transform: uppercase;
        letter-spacing: 1px;
        font-weight: 600;
    }
    
    /* Table Styling overrides */
    div[data-testid="stDataFrame"] {
        border-radius: 10px;
        border: 1px solid #2D3139;
        overflow: hidden;
    }
    
    /* Header Enhancements */
    h1 {
        font-weight: 800 !important;
        background: linear-gradient(90deg, #FFFFFF 0%, #A5B4FC 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
    }
</style>
""", unsafe_allow_html=True)

# ----------------------------------------------------------------------
# Data Loading
# ----------------------------------------------------------------------
@st.cache_data(ttl=60) # Cache for 1 minute
def load_data():
    """Load the dataset generated by the execution pipeline."""
    data_path = os.path.join(".tmp", "dashboard_dataset.csv")
    if os.path.exists(data_path):
        df = pd.read_csv(data_path)
        # Ensure correct types
        if 'Posted' in df.columns:
            df['Posted'] = pd.to_datetime(df['Posted'], errors='coerce')
        return df
    else:
        # Return empty dataframe with exact 14 requested columns
        return pd.DataFrame(columns=[
            'Company', 'Job Title', 'Job Description', 'Location', 
            'Employment type', 'Experience', 'Posted', 'first_seen_date', 'Job url', 
            'Source', 'Industry', 'Intensity', 'ERP', 'Timestamp'
        ])

def run_app():
    # Header
    st.title("💼 Rhocash AP Hiring Intelligence Dashboard")
    st.markdown("Automated tracking of US companies actively hiring for Accounts Payable roles.")
    
    # Load dataset
    df = load_data()
    
    if df.empty:
        st.info("ℹ️ Dataset is currently empty. Use the **Run Scraper Now** button in the sidebar to populate the dashboard with fresh leads.")

    # ----------------------------------------------------------------------
    # Sidebar: Scrape Controls
    # ----------------------------------------------------------------------
    st.sidebar.markdown('### ⚡ Live Data Mining')
    
    # Persistent storage for scheduler & manual state
    if "scheduler_active" not in st.session_state:
        st.session_state["scheduler_active"] = False
        st.session_state["schedule_type"] = None
        
    if "runs_today" not in st.session_state:
        st.session_state["runs_today"] = 0
        
    if "abort_scrape" not in st.session_state:
        st.session_state["abort_scrape"] = False
        
    if "admin" not in st.session_state:
        st.session_state["admin"] = False
        
    # Check for admin unlock
    admin_code = os.getenv("ADMIN_CODE")
    
    with st.sidebar.expander("Control Panel", expanded=st.session_state.get("admin", False)):
        if not st.session_state.get("admin"):
            st.warning("🔒 Admin Access Required")
        else:
            st.markdown("<small>Manage automated scraping pipelines.</small>", unsafe_allow_html=True)
        
        # 1. Manual Run
        runs = st.session_state["runs_today"]
        st.markdown(f"**Manual Scraper** *(Used {runs} time{'s' if runs != 1 else ''} today)*")
        
        col1, col2 = st.columns([2, 1])
        start_btn = col1.button("▶️ Run Scraper", use_container_width=True, type="primary")
        stop_btn = col2.button("🚫 Stop", use_container_width=True, type="secondary")
        
        if stop_btn:
            st.session_state["abort_scrape"] = True
            st.warning("Sending Stop Signal to Scraper... (Will halt after current step)")
            
        if start_btn:
            st.session_state["abort_scrape"] = False
            st.session_state["runs_today"] += 1
            progress_bar = st.progress(0)
            status_text = st.empty()
            
            import subprocess
            import time
            
            # Create a live terminal window
            st.markdown("---")
            terminal_expander = st.expander("🖥️ Live Execution Logs", expanded=True)
            log_output = terminal_expander.empty()
            full_logs = ""
            
            def run_and_stream(command, step_msg, progress_pct):
                nonlocal full_logs
                
                # Check for abort BEFORE starting step
                if st.session_state.get("abort_scrape"):
                    return False
                    
                status_text.info(step_msg)
                
                # Start process with pipe
                process = subprocess.Popen(
                    command, 
                    stdout=subprocess.PIPE, 
                    stderr=subprocess.STDOUT, 
                    text=True, 
                    bufsize=1, 
                    universal_newlines=True
                )
                
                # Read line by line as it comes in
                for line in iter(process.stdout.readline, ""):
                    # Check for abort DURING step
                    if st.session_state.get("abort_scrape"):
                        process.terminate() # Kill the pipeline child process
                        return False
                        
                    cleaned_line = line.strip().split(' - ', 1)[-1] 
                    if cleaned_line:
                        full_logs += f"> {cleaned_line}\n"
                        short_logs = "\n".join(full_logs.split('\n')[-8:])
                        log_output.code(short_logs, language="bash")
                
                process.stdout.close()
                return_code = process.wait()
                
                if return_code != 0 and not st.session_state.get("abort_scrape"):
                    raise subprocess.CalledProcessError(return_code, command)
                    
                progress_bar.progress(progress_pct)
                return True

            try:
                # Run Steps and Stream Results
                success = True
                if success: success = run_and_stream(["python", "execution/run_apify_scraper.py"], "⏳ Step 1/5: Running Apify Cloud Scraper... (Connecting to cloud...)", 40)
                if success: success = run_and_stream(["python", "execution/process_jobs.py"], "⏳ Step 2/5: Cleaning and Deduplicating leads...", 60)
                if success: success = run_and_stream(["python", "execution/calculate_hiring_intensity.py"], "⏳ Step 3/5: Calculating Hiring Intensity metrics...", 80)
                if success: success = run_and_stream(["python", "execution/generate_dashboard_data.py"], "⏳ Step 4/5: Generating dashboard analytics...", 90)
                if success: success = run_and_stream(["python", "execution/update_google_sheet.py"], "⏳ Step 5/5: Pushing fresh leads to Google Sheets...", 100)
                
                if st.session_state.get("abort_scrape"):
                    status_text.error("🛑 Scraping Pipeline Aborted by User.")
                    full_logs += "\n[SYSTEM] Run Terminated."
                    log_output.code("\n".join(full_logs.split('\n')[-8:]), language="bash")
                    st.session_state["abort_scrape"] = False # reset
                else:
                    status_text.success("✅ Pipeline Complete! Extracted, Cleaned, & Pushed successfully.")
                    full_logs += "\n[SYSTEM] Run Complete. Refreshing UI..."
                    log_output.code("\n".join(full_logs.split('\n')[-8:]), language="bash")
                    time.sleep(2)
                    st.rerun() 
                
            except subprocess.CalledProcessError as e:
                progress_bar.empty()
                status_text.error(f"**Pipeline Step Failed:** `{' '.join(e.cmd)}`")
                full_logs += f"\n[CRITICAL ERROR] Exit Code {e.returncode}"
                log_output.code(full_logs, language="bash")
                    
        st.markdown("---")
        
        # 2. Automated Scheduler
        st.markdown("**Automated Scraping**")
        st.info("🕒 Hardcoded Schedule: **Every Day at 10:00 PM IST**")
        
        pid_file = os.path.join(".tmp", "scheduler.pid")
        
        def stop_scheduler():
            if os.path.exists(pid_file):
                try:
                    with open(pid_file, "r") as f:
                        pid = int(f.read().strip())
                    import subprocess
                    # Using taskkill for Windows compatibility
                    subprocess.run(["taskkill", "/F", "/PID", str(pid)], capture_output=True)
                except Exception:
                    pass
                try:
                    os.remove(pid_file)
                except:
                    pass

        def start_scheduler():
            stop_scheduler() # kill any existing
            import subprocess
            p = subprocess.Popen(["python", "execution/scheduler.py"])
            with open(pid_file, "w") as f:
                f.write(str(p.pid))
        
        if st.session_state.get("scheduler_active") or os.path.exists(pid_file):
            if st.button("🛑 Stop Background Daemon", use_container_width=True, type="secondary"):
                stop_scheduler()
                st.session_state["scheduler_active"] = False
                st.success("Background automation disabled.")
                st.rerun()
        else:
            if st.button("▶️ Start Daily Daemon", use_container_width=True, type="primary"):
                start_scheduler()
                st.session_state["scheduler_active"] = True
                st.session_state["schedule_type"] = "10:00 PM IST"
                st.success(f"Background automation activated (10 PM IST)")
                st.rerun()
            
        if st.session_state.get("scheduler_active") or os.path.exists(pid_file):
            st.success(f"🔄 **Daemon Active:** Waiting for 10:00 PM IST...")
                
    st.sidebar.markdown("---")
        
    # 3. Operations & Goals Dashboard
    st.sidebar.markdown("### 📊 Goal Tracker")
    goal_target = 10000
    daily_target_goal = 200 # Daily Velocity Target
    
    current_leads = len(df) if not df.empty else 0
    today_str = pd.Timestamp.today().strftime('%Y-%m-%d')
    today_leads = len(df[df['first_seen_date'] == today_str]) if 'first_seen_date' in df.columns else 0
    
    # Ultimate 10k Goal
    progress_pct = min(current_leads / goal_target, 1.0)
    st.sidebar.progress(progress_pct, text=f"**{current_leads:,} / {goal_target:,} Lifetime Leads**")
    st.sidebar.caption(f"🏁 {(progress_pct*100):.2f}% to your 10k goal!")
    
    # Daily Goal Tracker
    daily_pct = min(today_leads / daily_target_goal, 1.0)
    st.sidebar.progress(daily_pct, text=f"**{today_leads:,} / {daily_target_goal:,} Leads Today**")
    st.sidebar.caption(f"📅 Daily extraction velocity metric")
    
    # Apify Quota Monitor (Client-side estimation / API Fetch)
    st.sidebar.markdown("### 🔌 Apify Quota Monitor")
    api_token = os.getenv("APIFY_API_TOKEN")
    if api_token:
        try:
            # Query Apify API for user limits and current usage
            resp = requests.get(f"https://api.apify.com/v2/users/me/limits?token={api_token}", timeout=5)
            if resp.status_code == 200:
                data = resp.json().get('data', {})
                limit_data = data.get('limits', {})
                limit = limit_data.get('maxMonthlyUsageUsd', limit_data.get('monthlyUsageUsd', 5.0))
                used = data.get('current', {}).get('monthlyUsageUsd', 0.0)
                
                st.sidebar.metric(
                    label="Monthly Credits Used", 
                    value=f"${used:.3f}", 
                    delta=f"${max(0, limit - used):.2f} remaining",
                    delta_color="normal"
                )
                
                if used >= limit:
                    st.sidebar.error("⚠️ Apify Credits Exhausted! Runs will fail.")
                else:
                    runs_left_est = int((limit - used) / 0.015) # Avg $0.015 per scrape
                    st.sidebar.success(f"Est. {runs_left_est} free scrapes remaining this month.")
            else:
                st.sidebar.warning(f"Failed to fetch live API quota (Status: {resp.status_code}).")
        except Exception:
            st.sidebar.warning("Could not connect to Apify servers.")
    else:
         st.sidebar.info("Add API_TOKEN to .env to see live quota.")
    
    # ----------------------------------------------------------------------
    # Sidebar: Filters
    # ----------------------------------------------------------------------
    st.sidebar.header("Filter Data")
    
    # Safely get Location filter
    # Extract just the State from "City, ST" for the filter UI if possible
    def get_state(loc):
        loc_str = str(loc)
        return loc_str.split(',')[-1].strip() if ',' in loc_str else loc_str
        
    df['FilterState'] = df['Location'].apply(get_state) if 'Location' in df.columns else 'Unknown'
    
    all_states = sorted(df['FilterState'].unique().tolist())
    selected_states = st.sidebar.multiselect("Select State/Region", all_states, default=all_states)
    
    # Intensity Filter
    all_intensities = ["High", "Medium", "Low", "Unknown"]
    available_intensities = [i for i in all_intensities if i in df['Intensity'].unique()] if 'Intensity' in df.columns else []
    selected_intensities = st.sidebar.multiselect("Hiring Intensity", available_intensities, default=available_intensities)

    # ERP Filter
    if 'ERP' in df.columns:
        # Get all unique comma-separated ERPs, flatten, and dedup
        all_erps = set()
        for x in df['ERP'].dropna():
            if str(x) != 'Unknown' and str(x) != '':
                for erp in str(x).split(','):
                    all_erps.add(erp.strip())
        
        all_erps = sorted(list(all_erps))
        if not all_erps:
            all_erps = ["Unknown"]
            
        selected_erps = st.sidebar.multiselect("ERP System Used", all_erps, default=all_erps)
        
        # We need a custom mask because ERPs are comma-separated strings inside the column
        def has_selected_erp(val):
            if not isinstance(val, str): return False
            val_list = [v.strip() for v in val.split(',')]
            return any(e in val_list for e in selected_erps)
            
        erp_mask = df['ERP'].apply(has_selected_erp) if selected_erps else pd.Series(True, index=df.index)
    else:
        erp_mask = pd.Series(True, index=df.index)

    # Apply Filters
    mask = (
        df['FilterState'].isin(selected_states) &
        df.get('Intensity', pd.Series('Unknown', index=df.index)).isin(selected_intensities) &
        erp_mask
    )
    filtered_df = df[mask].copy()

    # ----------------------------------------------------------------------
    # Top Level Metrics
    # ----------------------------------------------------------------------
    st.markdown("### 📊 Key Metrics")
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        st.markdown(f"""
            <div class="metric-card">
                <div class="metric-value">{len(filtered_df):,}</div>
                <div class="metric-label">Total Jobs Identified</div>
            </div>
        """, unsafe_allow_html=True)
        
    with col2:
        unique_companies = filtered_df['Company'].nunique() if (not filtered_df.empty and 'Company' in filtered_df.columns) else 0
        st.markdown(f"""
            <div class="metric-card">
                <div class="metric-value">{unique_companies:,}</div>
                <div class="metric-label">Unique Companies</div>
            </div>
        """, unsafe_allow_html=True)
        
    with col3:
        if not filtered_df.empty and 'Intensity' in filtered_df.columns and 'Company' in filtered_df.columns:
            high_intensity = filtered_df[filtered_df['Intensity'] == 'High']['Company'].nunique()
        else:
            high_intensity = 0
            
        st.markdown(f"""
            <div class="metric-card">
                <div class="metric-value">{high_intensity:,}</div>
                <div class="metric-label">Power Hirers (5+ Jobs)</div>
            </div>
        """, unsafe_allow_html=True)
        
    with col4:
        states_covered = filtered_df['FilterState'].nunique() if (not filtered_df.empty and 'FilterState' in filtered_df.columns) else 0
        st.markdown(f"""
            <div class="metric-card">
                <div class="metric-value">{states_covered}</div>
                <div class="metric-label">Regions Covered</div>
            </div>
        """, unsafe_allow_html=True)

    st.markdown("---")

    if not df.empty:
        # ----------------------------------------------------------------------
        # Charts & Visualizations
        # ----------------------------------------------------------------------
        st.markdown("### 📈 Visual Analytics")
        chart_col1, chart_col2 = st.columns(2)
        
        with chart_col1:
            # Jobs by State
            state_counts = filtered_df['FilterState'].value_counts().reset_index()
            state_counts.columns = ['Region', 'Job Count']
            if not state_counts.empty:
                fig_state = px.bar(
                    state_counts.head(15), 
                    x='Region', 
                    y='Job Count', 
                    title='Top 15 Regions by Job Volume',
                    color='Job Count',
                    color_continuous_scale=px.colors.sequential.Tealgrn,
                    template="plotly_dark"
                )
                fig_state.update_layout(plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)")
                st.plotly_chart(fig_state, use_container_width=True)
            else:
                st.info("Not enough data for chart")
            
        with chart_col2:
            # Hiring Intensity Distribution
            if 'Intensity' in filtered_df.columns and not filtered_df.empty:
                intensity_counts = filtered_df['Intensity'].value_counts().reset_index()
                intensity_counts.columns = ['Intensity', 'Count']
                fig_intensity = px.pie(
                    intensity_counts, 
                    names='Intensity', 
                    values='Count', 
                    title='Hiring Intensity Breakdown',
                    hole=0.5,
                    color='Intensity',
                    color_discrete_map={'High': '#DC2626', 'Medium': '#F59E0B', 'Low': '#3B82F6', 'Unknown': '#6B7280'},
                    template="plotly_dark"
                )
                fig_intensity.update_layout(plot_bgcolor="rgba(0,0,0,0)", paper_bgcolor="rgba(0,0,0,0)")
                st.plotly_chart(fig_intensity, use_container_width=True)
            else:
                st.info("Not enough data for chart")

        # ----------------------------------------------------------------------
        # Detailed Data Table
        # ----------------------------------------------------------------------
        st.markdown("### 📋 Lead Explorer")
        st.markdown("Search, sort, and explore individual job leads.")
        
        # Display dataframe using all requested columns in order
        display_cols = [
            'Company', 'Job Title', 'Job Description', 'ERP', 'Location', 
            'Employment type', 'Experience', 'Posted', 'first_seen_date', 'Job url', 
            'Source', 'Industry', 'Intensity', 'Timestamp'
        ]
        # Truncate dataset for public preview unless Admin
        if st.session_state.get("admin"):
            display_df = filtered_df[[c for c in display_cols if c in filtered_df.columns]]
        else:
            st.info("🔒 Showing 50 row preview. Enter Client Access Code to unlock full dataset.")
            display_df = filtered_df[[c for c in display_cols if c in filtered_df.columns]].head(50)
            
        st.dataframe(
            display_df,
            use_container_width=True,
            hide_index=True,
            height=500
        )

    # ----------------------------------------------------------------------
    # Downloads Section (Admin Only)
    # ----------------------------------------------------------------------
    st.sidebar.markdown("---")
    
    if st.session_state.get("admin"):
        st.sidebar.markdown("### 📥 Export Leads")
        
        # Generate CSV strings
        @st.cache_data
        def convert_df(df_to_convert):
            return df_to_convert.to_csv(index=False).encode('utf-8')

        # Generate Excel strings
        @st.cache_data
        def convert_df_to_excel(df_to_convert):
            output = io.BytesIO()
            with pd.ExcelWriter(output, engine='openpyxl') as writer:
                df_to_convert.to_excel(writer, index=False, sheet_name='Leads')
            return output.getvalue()

        # Full Dataset Download
        st.sidebar.markdown("**Full Dataset**")
        col1, col2 = st.sidebar.columns(2)
        col1.download_button(
            label="CSV",
            data=convert_df(df),
            file_name='rhocash_ap_all_leads.csv',
            mime='text/csv',
            use_container_width=True
        )
        col2.download_button(
            label="Excel",
            data=convert_df_to_excel(df),
            file_name='rhocash_ap_all_leads.xlsx',
            mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            use_container_width=True
        )
        
        # High Intensity leads Download
        if 'Intensity' in df.columns:
            high_df = df[df['Intensity'] == 'High']
            if not high_df.empty:
                st.sidebar.markdown("**High-Intensity Leads**")
                col_h1, col_h2 = st.sidebar.columns(2)
                col_h1.download_button(
                    label="CSV",
                    data=convert_df(high_df),
                    file_name='rhocash_ap_high_intensity.csv',
                    mime='text/csv',
                    use_container_width=True
                )
                col_h2.download_button(
                    label="Excel",
                    data=convert_df_to_excel(high_df),
                    file_name='rhocash_ap_high_intensity.xlsx',
                    mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                    use_container_width=True
                )
        
        # Historical Leads Download (filtered dynamically by date)
        st.sidebar.markdown("---")
        st.sidebar.markdown("**Custom Date Range**")
        date_range = st.sidebar.date_input(
            "Select Range", 
            value=[pd.Timestamp.today().date(), pd.Timestamp.today().date()],
            help="Download leads discovered within this timeframe"
        )
        
        if isinstance(date_range, list) and len(date_range) == 2:
            start_date, end_date = date_range
            mask = (pd.to_datetime(df['first_seen_date']).dt.date >= start_date) & \
                   (pd.to_datetime(df['first_seen_date']).dt.date <= end_date)
            range_df = df[mask]
            
            st.sidebar.info(f"📍 {len(range_df)} leads found in range.")
            
            col_r1, col_r2 = st.sidebar.columns(2)
            col_r1.download_button(
                label="CSV",
                data=convert_df(range_df),
                file_name=f'rhocash_leads_{start_date}_to_{end_date}.csv',
                mime='text/csv',
                use_container_width=True
            )
            col_r2.download_button(
                label="Excel",
                data=convert_df_to_excel(range_df),
                file_name=f'rhocash_leads_{start_date}_to_{end_date}.xlsx',
                mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                use_container_width=True
            )

    else:
        # ----------------------------------------------------------------------
        # Client Login Box
        # ----------------------------------------------------------------------
        st.sidebar.markdown("### 🔐 Client Login")
        entered_code = st.sidebar.text_input("Enter Access Code:", type="password")
        if entered_code:
            if entered_code == admin_code and admin_code is not None:
                st.session_state["admin"] = True
                st.rerun()
            else:
                st.sidebar.error("Invalid Code")

if __name__ == "__main__":
    run_app()
